/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import pares_impares.primo; 
import javax.swing.JOptionPane;



/**
 *
 * @author Instructor
 */
public class Formulario_primo extends javax.swing.JFrame {
    java.util.LinkedList Nprimos = new java.util.LinkedList();

    /**
     * Creates new form Formulario_primo
     */
    public Formulario_primo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_numeros = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        numero_espacio = new javax.swing.JTextField();
        calcular_boton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        cperfectos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        numeros_perfectos = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("PRIMOS");

        lista_numeros.setColumns(20);
        lista_numeros.setRows(5);
        jScrollPane1.setViewportView(lista_numeros);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Numero: ");

        numero_espacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_espacioActionPerformed(evt);
            }
        });

        calcular_boton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcular_boton.setText("PRIMOS");
        calcular_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_botonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Numeros Primos");

        tiempo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tiempo.setText("Tiempo");

        cperfectos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cperfectos.setText("PERFECTOS");
        cperfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cperfectosActionPerformed(evt);
            }
        });

        numeros_perfectos.setColumns(20);
        numeros_perfectos.setRows(5);
        jScrollPane2.setViewportView(numeros_perfectos);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Numeros Perfectos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel5)
                        .addGap(284, 284, 284)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71)
                        .addComponent(numero_espacio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cperfectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcular_boton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiempo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numero_espacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(cperfectos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(tiempo)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero_espacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_espacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_espacioActionPerformed

    private void calcular_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_botonActionPerformed
        // TODO add your handling code here:
long num = Long.parseLong(numero_espacio.getText().trim());
    
        long tinicial = System.currentTimeMillis();
        long tfinal = 0;

        for (long i = 2; i <= num; i++) {
            if (num_P(i)) {
                lista_numeros.append("Numero primo: " + i + "\n");
            }
        }
        tfinal = System.currentTimeMillis();
        long treal = tfinal - tinicial;
        treal = treal / 1000;
        tiempo.setText(String.valueOf(treal));
    }

    private boolean num_P(long numero) {
        if (numero <= 1) {
            return false;

        }

        for (long i = 2; i <= Math.sqrt(numero); i++) {
            if (numero % i == 0) {
                return false;
            }
        }
        return true;


   
                
            

    
    
    
        
        
            
    }//GEN-LAST:event_calcular_botonActionPerformed

    private void cperfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cperfectosActionPerformed
        // TODO add your handling code here:
        
        long limite = Long.parseLong(numero_espacio.getText());
        
        long tinical = System.currentTimeMillis();
        long tfinal = 0;
        
        for (long e=0; e<=limite; e++){
         if (esPerfecto(e)){
             numeros_perfectos.append("numeros perfectos=" +e+"\n");
         
         }
         tfinal = System.currentTimeMillis();
         long te = tfinal - tinical;
        tiempo.setText(String.valueOf( te / 1000));
        }
        
        
        
        
    }                                         
private boolean esPerfecto(long e){
int suma=1;
   for(int divisor =2;divisor*divisor<=e;divisor++){
   if (e % divisor ==0){
       suma +=divisor;
      if (divisor !=e/divisor){
          suma += e / divisor;
      }
   }
   }
   return suma==e;
    }//GEN-LAST:event_cperfectosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_primo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_primo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_primo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_primo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_primo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular_boton;
    private javax.swing.JButton cperfectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lista_numeros;
    private javax.swing.JTextField numero_espacio;
    private javax.swing.JTextArea numeros_perfectos;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
